### ISSUE TITLE
uinput.c - No longer compiles  - NAN related error

### ISSUE THREAD

**Issue by roeyaus** [santigimeno/node-uinput#1]
getting this trying to "npm install uinput" : 

../src/uinput.cpp: In function ‘void {anonymous}::Initialize(v8::Localv8::Object)’:
../src/uinput.cpp:1396:38: error: call of overloaded ‘New(long unsigned int)’ is ambiguous
                 Nan::New(UI_SET_EVBIT));
                                      ^
../src/uinput.cpp:1396:38: note: candidates are:
In file included from ../node_modules/nan/nan.h:188:0,
                 from ../src/uinput.cpp:1:

etc etc

**Comment by michaelschleiss** [comment]
Same problem here.

**Comment by santigimeno** [comment]
Sorry for the late response.
Indeed, it's not working in 64bit OS. I'll try to fix it as soon as I can. Cheers

**Comment by santigimeno** [comment]
@roeyaus @michaelschleiss, does https://github.com/santigimeno/node-uinput/pull/2 fix it for you?

**Comment by michaelschleiss** [comment]
Thanks, this fixed the issue for me.

**Comment by santigimeno** [comment]
Fixed in `0.0.4`. Thanks!
